INSERT INTO produce (name, emoji)
VALUES ('Apple', '🍏'),
       ('Apple', '🍎'),
       ('Pear', '🍐'),
       ('Orange', '🍊'),
       ('Lemon', '🍋'),
       ('Banana', '🍌'),
       ('Watermelon', '🍉'),
       ('Grape', '🍇'),
       ('Strawberry', '🍓'),
       ('Blueberry', '🫐'),
       ('Melon', '🍈'),
       ('Cherry', '🍒'),
       ('Peach', '🍑'),
       ('Mango', '🥭'),
       ('Pineapple', '🍍'),
       ('Coconut', '🥥'),
       ('Kiwi', '🥝'),
       ('Tomato', '🍅'),
       ('Olive', '🫒'),
       ('Avocado', '🥑'),
       ('Eggplant', '🍆'),
       ('Potato', '🥔'),
       ('Yam', '🍠'),
       ('Carrot', '🥕'),
       ('Corn', '🌽'),
       ('Chili', '🌶️'),
       ('Bell Pepper', '🫑'),
       ('Cucumber', '🥒'),
       ('Leafy Green', '🥬'),
       ('Broccoli', '🥦'),
       ('Garlic', '🧄'),
       ('Onion', '🧅'),
       ('Peas', '🫛'),
       ('Beans', '🫘'),
       ('Chestnut', '🌰'),
       ('Ginger', '🫚');

